#!/bin/bash

job_setup_hardware()
{

	msg_job_start "job_setup_hardware"

	mount -v -t proc none ${mountpoint}/proc 
	mount -v -t sysfs none ${mountpoint}/sys 
	mount -v -o bind /dev ${mountpoint}/dev 

	# remove any db.lck
	chroot ${mountpoint} /bin/rm -f /var/lib/pacman/db.lck
	
	# setup alsa volume levels
	msg "setup alsa config"
	if [ -e "/etc/asound.state" ] ; then
		cp -v -a -f /etc/asound.state ${mountpoint}/etc/asound.state
	fi

	# alsa blacklist for the pc speaker
	if [ -e "/etc/modprobe.d/alsa_blacklist.conf" ] ; then
		cp -v -a -f /etc/modprobe.d/alsa_blacklist.conf ${mountpoint}/etc/modprobe.d/alsa_blacklist.conf
	fi

	# blacklist for broken realtek nics
	if [ -e "/etc/modprobe.d/realtek_blacklist.conf" ] ; then
		cp -v -a -f /etc/modprobe.d/realtek_blacklist.conf ${mountpoint}/etc/modprobe.d/realtek_blacklist.conf
	fi

	# setup proprietary drivers, if detected
	msg "setup proprietary drivers"
	if [ -e "/tmp/nvidia" ] ; then
		msg "nvidia detected"

		msg "removing unneeded packages"
		chroot ${mountpoint} /usr/bin/pacman -Rdd libgl --noconfirm
		chroot ${mountpoint} /usr/bin/pacman -Rdd nouveau-dri --noconfirm
		chroot ${mountpoint} /usr/bin/pacman -Rdd xf86-nv --noconfirm
		chroot ${mountpoint} /usr/bin/pacman -Rdd xf86-nouveau --noconfirm
		msg "installing driver"
		pacman -r ${mountpoint} -Udf ${PKG_OVERLAY}/nvidia-utils-3* --noconfirm
		pacman -r ${mountpoint} -Udf ${PKG_OVERLAY}/nvidia-3* --noconfirm

		# load the modules array from rc.conf
		#msg "loading current modules from rc.conf"
		#RCCONF_MODULES=`cat ${mountpoint}/etc/rc.conf | grep "MODULES=" | cut -d "(" -f 2 | cut -d ")" -f 1`

		# add the detected modules to the original modules array
		#msg "adding nvidia module to modules array"
		#NEW_RCCONF_MODULES=`echo "MODULES=($RCCONF_MODULES nvidia)" | sed 's/  / /g'`

		# and put that into rc.conf
		#msg "writing new rc.conf"
		#sed -i -e "s,MODULES=.*,$NEW_RCCONF_MODULES,g" ${mountpoint}/etc/rc.conf

		#unset RCCONF_MODULES
		#unset NEW_RCCONF_MODULES

	elif [ -e "/tmp/nvidia-173xx" ] ; then
		msg "nvidia-173xx detected"

		msg "removing unneeded packages"
		chroot ${mountpoint} /usr/bin/pacman -Rdd libgl --noconfirm
		chroot ${mountpoint} /usr/bin/pacman -Rdd nouveau-dri --noconfirm
		chroot ${mountpoint} /usr/bin/pacman -Rdd xf86-nv --noconfirm
		chroot ${mountpoint} /usr/bin/pacman -Rdd xf86-nouveau --noconfirm
		msg "installing driver"
		pacman -r ${mountpoint} -Udf ${PKG_OVERLAY}/nvidia-173xx* --noconfirm

		# load the modules array from rc.conf
		#msg "loading current modules from rc.conf"
		#RCCONF_MODULES=`cat ${mountpoint}/etc/rc.conf | grep "MODULES=" | cut -d "(" -f 2 | cut -d ")" -f 1`

		# add the detected modules to the original modules array
		#msg "adding nvidia module to modules array"
		#NEW_RCCONF_MODULES=`echo "MODULES=($RCCONF_MODULES nvidia)" | sed 's/  / /g'`

		# and put that into rc.conf
		#msg "writing new rc.conf"
		#sed -i -e "s,MODULES=.*,$NEW_RCCONF_MODULES,g" ${mountpoint}/etc/rc.conf

		#unset RCCONF_MODULES
		#unset NEW_RCCONF_MODULES

	elif [ -e "/tmp/catalyst" ] ; then
		msg "catalyst detected" 

		msg "removing unneeded packages"
		# remove conflicting packages
		chroot ${mountpoint} /usr/bin/pacman -Rdd libgl --noconfirm
		chroot ${mountpoint} /usr/bin/pacman -Rdd nouveau-dri --noconfirm
		chroot ${mountpoint} /usr/bin/pacman -Rdd xf86-video-ati --noconfirm

		msg "installing driver"
		# install driver
		pacman -r ${mountpoint} -Udf ${PKG_OVERLAY}/catalyst-utils* --noconfirm
		pacman -r ${mountpoint} -Udf ${PKG_OVERLAY}/catalyst-1* --noconfirm

		# load the modules array from rc.conf
		#msg "loading current modules from rc.conf"
		#RCCONF_MODULES=`cat ${mountpoint}/etc/rc.conf | grep "MODULES=" | cut -d "(" -f 2 | cut -d ")" -f 1`

		# add the detected modules to the original modules array
		#msg "adding catalyst fglrx module to modules array"
		#NEW_RCCONF_MODULES=`echo "MODULES=($RCCONF_MODULES fglrx)" | sed 's/  / /g'`

		# and put that into rc.conf
		#msg "writing new rc.conf"
		#sed -i -e "s,MODULES=.*,$NEW_RCCONF_MODULES,g" ${mountpoint}/etc/rc.conf

		#unset RCCONF_MODULES
		#unset NEW_RCCONF_MODULES
		
	elif [ -e "/tmp/catalyst-legacy" ] ; then
		msg "catalyst-legacy detected" 

		msg "removing unneeded packages"
		# remove conflicting packages
		chroot ${mountpoint} /usr/bin/pacman -Rdd libgl --noconfirm
		chroot ${mountpoint} /usr/bin/pacman -Rdd nouveau-dri --noconfirm
		chroot ${mountpoint} /usr/bin/pacman -Rdd xf86-video-ati --noconfirm

		msg "installing driver"
		# install driver
		pacman -r ${mountpoint} -Udf ${PKG_OVERLAY}/catalyst-legacy-utils* --noconfirm
		pacman -r ${mountpoint} -Udf ${PKG_OVERLAY}/catalyst-legacy-1* --noconfirm
		
		# load the modules array from rc.conf
		#msg "loading current modules from rc.conf"
		#RCCONF_MODULES=`cat ${mountpoint}/etc/rc.conf | grep "MODULES=" | cut -d "(" -f 2 | cut -d ")" -f 1`

		# add the detected modules to the original modules array
		#msg "adding catalyst fglrx module to modules array"
		#NEW_RCCONF_MODULES=`echo "MODULES=($RCCONF_MODULES fglrx)" | sed 's/  / /g'`

		# and put that into rc.conf
		#msg "writing new rc.conf"
		#sed -i -e "s,MODULES=.*,$NEW_RCCONF_MODULES,g" ${mountpoint}/etc/rc.conf

		#unset RCCONF_MODULES
		#unset NEW_RCCONF_MODULES
	fi

	# fixing alsa
	alsactl -f ${mountpoint}/var/lib/alsa/asound.state store
	
	msg "umounting /proc, /sys and /dev"
	umount -v ${mountpoint}/proc ${mountpoint}/sys ${mountpoint}/dev 

	msg_job_done
}
