#!/bin/bash

job_set_hostname()
{
	# initialize error handling
	trap error_handler ERR

	msg_job_start "job_set_hostname"

	msg "set the hostname"
	if [ "${hostname}" != "" ] ; then
		msg "creating /etc/hostname with '${hostname}'"
		echo "${hostname}" > ${mountpoint}/etc/hostname
		msg "updating /etc/hosts"
		sed -i -e 's/^[ \t]*127.0.0.1.*/127.0.0.1\tlocalhost.localdomain\tlocalhost\t'${hostname}'/' ${mountpoint}/etc/hosts
	else
		msg "creating /etc/hostname with 'kdeos' (no hostname specified)"
		echo "kdeos" > ${mountpoint}/etc/hostname
		msg "updating /etc/hosts"
		sed -i -e 's/^[ \t]*127.0.0.1.*/127.0.0.1\tlocalhost.localdomain\tlocalhost\tkdeos/' ${mountpoint}/etc/hosts
	fi

	msg_job_done
} 
